# Generated by Django 2.0.5 on 2019-12-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_chat', models.NullBooleanField(default=False, verbose_name='Группа')),
                ('topic', models.CharField(default='Chat', max_length=64, verbose_name='Заголовок')),
                ('last_message', models.TextField(default='', verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='Содержание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('image_key', models.TextField(default='', verbose_name='Ключ для изображения')),
                ('image_mime_type', models.TextField(default='', verbose_name='MIME тип изображения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReadedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message', models.IntegerField(default=-1)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat')),
            ],
        ),
    ]
