# Generated by Django 2.0.5 on 2019-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191203_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_date',
            field=models.TextField(default='', verbose_name='Время последнего сообщения'),
        ),
    ]
