# Generated by Django 2.2.5 on 2019-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name': 'Сообщение', 'verbose_name_plural': ''},
        ),
    ]
