# Generated by Django 2.2.5 on 2019-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20191113_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, null=True, verbose_name='Прочитано'),
        ),
    ]
