# Generated by Django 2.2.5 on 2019-11-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_message_is_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_readed',
            new_name='is_read',
        ),
    ]
