# Generated by Django 2.2.5 on 2019-11-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191120_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
