# Generated by Django 2.2.5 on 2019-11-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_key',
            field=models.TextField(default='', verbose_name='Ключ для изображения'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_mime_type',
            field=models.TextField(default='', verbose_name='MIME тип изображения'),
        ),
    ]
