# Generated by Django 2.2.5 on 2019-11-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_auto_20191130_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readedmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat'),
        ),
        migrations.AlterField(
            model_name='readedmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
