# Generated by Django 2.2.5 on 2019-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nick', models.CharField(max_length=64)),
                ('avatar', models.CharField(default='', max_length=256)),
                ('chat', models.ManyToManyField(to='chats.Chat')),
            ],
        ),
    ]
