# Generated by Django 2.2.5 on 2019-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191105_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat',
        ),
    ]
