# Generated by Django 2.2.5 on 2019-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191113_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_read_message',
            field=models.IntegerField(default=-1, verbose_name='Последнее прочитанное сообщение id'),
        ),
    ]
