version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./chat_by_nikita/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runsslserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./chat_by_nikita:/chat_by_nikita
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
